window.tests = [
  'attribute-style-precedence',
  'clippath',
  'clippath-empty',
  'clippath-svg',
  'complete-bpmn',
  'complete-computer-network',
  'complete-dependency-diagram',
  'complete-diagram1',
  'complete-diagram2',
  'complete-dropshadows',
  'complete-flowchart1',
  'complete-flowchart2',
  'complete-movies',
  'complete-organization-chart',
  'complete-organization-chart-new',
  'complete-social-network',
  'custom-fonts',
  'display-none-and-visibility-inheritance',
  'duplicate-ids',
  'empty-elements',
  'fill-and-stroke-inheritance',
  'fill-and-stroke-opacity',
  'fill-and-stroke-rgba',
  'fill-rule',
  'font-family-attribute',
  'font-style',
  'gradient-default-coordinates',
  'gradient-percent-offset',
  'gradient-stop-defaults',
  'gradient-units',
  'gradients-and-patterns-mixed',
  'hidden-clippath',
  'image-aspect-ratio',
  'image-data-urls-base64-spaces',
  'image-svg-urls',
  'line-default-coordinates',
  'markers',
  'nested-tspans',
  'opacity-and-rgba',
  'path-arc-support',
  'pattern-units',
  'patterns',
  'polyline',
  'rect',
  'references',
  'remote-images',
  ['size-options/no-params-no-attrs-no-viewbox', [400, 300], {}],
  ['size-options/no-params-no-attrs-with-viewbox', [400, 300], {}],
  ['size-options/no-params-with-attrs-no-viewbox', [400, 300], {}],
  ['size-options/no-params-with-attrs-with-viewbox', [400, 300], {}],
  ['size-options/no-params-with-height-with-viewbox', [400, 300], {}],
  ['size-options/no-params-with-width-with-viewbox', [400, 300], {}],
  ['size-options/with-params-with-attrs-with-viewbox', [400, 300], { width: 250, height: 200 }],
  'strokes-and-bounding-boxes',
  'style-sheets',
  'svg-viewbox',
  'svg-use',
  'svg-use-empty',
  'symbols',
  'text-fill-stroke',
  'text-placement',
  'title-element',
  'transforms-parsing',
  'transparent-pngs',
  'url-references-with-quotes',
  'vertical-align',
  'xml-space',
  'zero-width-strokes',
  'zero-width-strokes-text',
  'current-color',
  'text-length',
  'group-fill-rule'
]
